// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app/build" | "/app/deploy" | "/app/discovery" | "/app/discovery/report" | "/app/discovery/review" | "/app/integrations" | "/app/onboarding" | "/app/onboarding/lean-canvas" | "/app/onboarding/voice-call" | "/app/planner" | "/app/planner/agents/[agentId]" | "/app/sandbox" | "/app/setup" | "/app/workspace" | "/app/workspace/agents" | "/app/workspace/approvals" | "/app/workspace/calendar" | "/app/workspace/integrations" | "/demo" | "/onboarding" | "/privacy" | "/terms"
type AppRouteHandlerRoutes = "/api/approvals/decision" | "/api/build/start" | "/api/call/complete" | "/api/deploy" | "/api/discovery/answer" | "/api/discovery/clarifications" | "/api/discovery/clarifications/answer" | "/api/discovery/questions" | "/api/discovery/session" | "/api/discovery/voice" | "/api/integrations/[organizationId]" | "/api/integrations/[organizationId]/[toolKey]/connect" | "/api/integrations/[organizationId]/[toolKey]/status" | "/api/onboarding/blueprint" | "/api/onboarding/discovery-agent" | "/api/onboarding/handoff" | "/api/onboarding/session" | "/api/onboarding/voice" | "/api/onboarding/voice/complete" | "/api/plan/apply-diff" | "/api/plan/approve" | "/api/plan/change" | "/api/plan/generate" | "/api/plan/nl" | "/api/plan/undo" | "/api/planner/[workforcePlanId]/approve" | "/api/planner/[workforcePlanId]/chat" | "/api/planner/[workforcePlanId]/chat/apply" | "/api/planner/[workforcePlanId]/cost-estimate" | "/api/planner/[workforcePlanId]/finalize-handoff" | "/api/planner/[workforcePlanId]/handoff" | "/api/planner/[workforcePlanId]/redo" | "/api/planner/[workforcePlanId]/undo" | "/api/planner/agent/[agentConfigId]/configure" | "/api/planner/agent/[agentConfigId]/design-call/clarify" | "/api/planner/agent/[agentConfigId]/design-call/start" | "/api/planner/agent/[agentConfigId]/design-call/turn" | "/api/planner/generate" | "/api/report" | "/api/report/approve" | "/api/report/handoff" | "/api/reset" | "/api/state" | "/api/transcribe" | "/api/validate" | "/api/voice/speak"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/demo"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/approvals/decision": {}
  "/api/build/start": {}
  "/api/call/complete": {}
  "/api/deploy": {}
  "/api/discovery/answer": {}
  "/api/discovery/clarifications": {}
  "/api/discovery/clarifications/answer": {}
  "/api/discovery/questions": {}
  "/api/discovery/session": {}
  "/api/discovery/voice": {}
  "/api/integrations/[organizationId]": { "organizationId": string; }
  "/api/integrations/[organizationId]/[toolKey]/connect": { "organizationId": string; "toolKey": string; }
  "/api/integrations/[organizationId]/[toolKey]/status": { "organizationId": string; "toolKey": string; }
  "/api/onboarding/blueprint": {}
  "/api/onboarding/discovery-agent": {}
  "/api/onboarding/handoff": {}
  "/api/onboarding/session": {}
  "/api/onboarding/voice": {}
  "/api/onboarding/voice/complete": {}
  "/api/plan/apply-diff": {}
  "/api/plan/approve": {}
  "/api/plan/change": {}
  "/api/plan/generate": {}
  "/api/plan/nl": {}
  "/api/plan/undo": {}
  "/api/planner/[workforcePlanId]/approve": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/chat": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/chat/apply": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/cost-estimate": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/finalize-handoff": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/handoff": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/redo": { "workforcePlanId": string; }
  "/api/planner/[workforcePlanId]/undo": { "workforcePlanId": string; }
  "/api/planner/agent/[agentConfigId]/configure": { "agentConfigId": string; }
  "/api/planner/agent/[agentConfigId]/design-call/clarify": { "agentConfigId": string; }
  "/api/planner/agent/[agentConfigId]/design-call/start": { "agentConfigId": string; }
  "/api/planner/agent/[agentConfigId]/design-call/turn": { "agentConfigId": string; }
  "/api/planner/generate": {}
  "/api/report": {}
  "/api/report/approve": {}
  "/api/report/handoff": {}
  "/api/reset": {}
  "/api/state": {}
  "/api/transcribe": {}
  "/api/validate": {}
  "/api/voice/speak": {}
  "/app": {}
  "/app/build": {}
  "/app/deploy": {}
  "/app/discovery": {}
  "/app/discovery/report": {}
  "/app/discovery/review": {}
  "/app/integrations": {}
  "/app/onboarding": {}
  "/app/onboarding/lean-canvas": {}
  "/app/onboarding/voice-call": {}
  "/app/planner": {}
  "/app/planner/agents/[agentId]": { "agentId": string; }
  "/app/sandbox": {}
  "/app/setup": {}
  "/app/workspace": {}
  "/app/workspace/agents": {}
  "/app/workspace/approvals": {}
  "/app/workspace/calendar": {}
  "/app/workspace/integrations": {}
  "/demo": {}
  "/onboarding": {}
  "/privacy": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/demo": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
