// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/app/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/build">> = Specific
  const handler = {} as typeof import("../../app/app/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/deploy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/deploy">> = Specific
  const handler = {} as typeof import("../../app/app/deploy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/discovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discovery">> = Specific
  const handler = {} as typeof import("../../app/app/discovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/discovery/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discovery/report">> = Specific
  const handler = {} as typeof import("../../app/app/discovery/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/discovery/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discovery/review">> = Specific
  const handler = {} as typeof import("../../app/app/discovery/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/integrations">> = Specific
  const handler = {} as typeof import("../../app/app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/onboarding/lean-canvas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding/lean-canvas">> = Specific
  const handler = {} as typeof import("../../app/app/onboarding/lean-canvas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding">> = Specific
  const handler = {} as typeof import("../../app/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/onboarding/voice-call/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding/voice-call">> = Specific
  const handler = {} as typeof import("../../app/app/onboarding/voice-call/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/planner/agents/[agentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/planner/agents/[agentId]">> = Specific
  const handler = {} as typeof import("../../app/app/planner/agents/[agentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/planner">> = Specific
  const handler = {} as typeof import("../../app/app/planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/sandbox">> = Specific
  const handler = {} as typeof import("../../app/app/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/setup">> = Specific
  const handler = {} as typeof import("../../app/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/workspace/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspace/agents">> = Specific
  const handler = {} as typeof import("../../app/app/workspace/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/workspace/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspace/approvals">> = Specific
  const handler = {} as typeof import("../../app/app/workspace/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/workspace/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspace/calendar">> = Specific
  const handler = {} as typeof import("../../app/app/workspace/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/workspace/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspace/integrations">> = Specific
  const handler = {} as typeof import("../../app/app/workspace/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspace">> = Specific
  const handler = {} as typeof import("../../app/app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/approvals/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals/decision">> = Specific
  const handler = {} as typeof import("../../app/api/approvals/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/build/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/build/start">> = Specific
  const handler = {} as typeof import("../../app/api/build/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/call/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/call/complete">> = Specific
  const handler = {} as typeof import("../../app/api/call/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deploy">> = Specific
  const handler = {} as typeof import("../../app/api/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/answer">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/clarifications/answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/clarifications/answer">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/clarifications/answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/clarifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/clarifications">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/clarifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/questions">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/session">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/voice">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/[organizationId]/[toolKey]/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[organizationId]/[toolKey]/connect">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/[organizationId]/[toolKey]/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/[organizationId]/[toolKey]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[organizationId]/[toolKey]/status">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/[organizationId]/[toolKey]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/[organizationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[organizationId]">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/[organizationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/blueprint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/blueprint">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/blueprint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/discovery-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/discovery-agent">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/discovery-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/handoff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/handoff">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/handoff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/session">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/voice/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/voice/complete">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/voice/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/voice">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/apply-diff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/apply-diff">> = Specific
  const handler = {} as typeof import("../../app/api/plan/apply-diff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/approve">> = Specific
  const handler = {} as typeof import("../../app/api/plan/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/change">> = Specific
  const handler = {} as typeof import("../../app/api/plan/change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/generate">> = Specific
  const handler = {} as typeof import("../../app/api/plan/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/nl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/nl">> = Specific
  const handler = {} as typeof import("../../app/api/plan/nl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan/undo">> = Specific
  const handler = {} as typeof import("../../app/api/plan/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/chat/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/chat/apply">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/chat/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/chat">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/cost-estimate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/cost-estimate">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/cost-estimate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/finalize-handoff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/finalize-handoff">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/finalize-handoff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/handoff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/handoff">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/handoff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/redo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/redo">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/redo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/[workforcePlanId]/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/[workforcePlanId]/undo">> = Specific
  const handler = {} as typeof import("../../app/api/planner/[workforcePlanId]/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/agent/[agentConfigId]/configure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/agent/[agentConfigId]/configure">> = Specific
  const handler = {} as typeof import("../../app/api/planner/agent/[agentConfigId]/configure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/agent/[agentConfigId]/design-call/clarify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/agent/[agentConfigId]/design-call/clarify">> = Specific
  const handler = {} as typeof import("../../app/api/planner/agent/[agentConfigId]/design-call/clarify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/agent/[agentConfigId]/design-call/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/agent/[agentConfigId]/design-call/start">> = Specific
  const handler = {} as typeof import("../../app/api/planner/agent/[agentConfigId]/design-call/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/agent/[agentConfigId]/design-call/turn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/agent/[agentConfigId]/design-call/turn">> = Specific
  const handler = {} as typeof import("../../app/api/planner/agent/[agentConfigId]/design-call/turn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner/generate">> = Specific
  const handler = {} as typeof import("../../app/api/planner/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/report/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report/approve">> = Specific
  const handler = {} as typeof import("../../app/api/report/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/report/handoff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report/handoff">> = Specific
  const handler = {} as typeof import("../../app/api/report/handoff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report">> = Specific
  const handler = {} as typeof import("../../app/api/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset">> = Specific
  const handler = {} as typeof import("../../app/api/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/state">> = Specific
  const handler = {} as typeof import("../../app/api/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/validate">> = Specific
  const handler = {} as typeof import("../../app/api/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voice/speak/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/speak">> = Specific
  const handler = {} as typeof import("../../app/api/voice/speak/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
